#!/usr/bin/env bash

op=$( echo -e " Poweroff\n Reboot\n Suspend\n Lock\n Logout" | fuzzel --dmenu | awk '{print tolower($2)}' )

case $op in 
        poweroff)
                systemctl poweroff
                ;;
        reboot)
                systemctl reboot
                ;;
        suspend)
                systemctl suspend, mode "default"
                ;;
        lock)
		        swaylock
                ;;
        logout)
                swaymsg exit
                ;;
esac